### ISSUE TITLE
lack lib

### ISSUE THREAD

**Issue by youjunhave** [awesomejerry/react-native-qrcode-svg#1]
I try to link lib, But Xcod without RCTFont lib,and Xcod cann't run.

**Comment by awesomejerry** [comment]
Have you linked react-native-svg? Haven't been testing this module for a long time. Will find time to give it a update. PRs are welcomed though :)

**Comment by youjunhave** [comment]
Thanks! I look forward to your updates.

**Comment by awesomejerry** [comment]
Updated. Please try it and see if it works for you. And remember to install react-native-svg as the dependency.

**Comment by youjunhave** [comment]
Thanks again! I try it, and Success! I think svg is better than webview.

**Comment by awesomejerry** [comment]
Yes, and that's why I built this. WebView is too slow :P
