### ISSUE TITLE
Any plans for "node-qrcode-svg"

### ISSUE THREAD

**Issue by michaelswe** [awesomejerry/react-native-qrcode-svg#10]
I need to generate QR codes on my server (node.js). It could be accomplished by using about 90% of the code in react-native-qrcode-svg. I was wondering if you already have such a project laying around or of I should fork and make one on my own.

**Comment by awesomejerry** [comment]
Hi @michaelswe , feel free to do whatever you want :) I currently don't have a plan of migrating it to node.js environment, although, if you need any help, please let me know!

**Comment by michaelswe** [comment]
Thanks.
I’m almost done :)

I’m keeping it in a git repo for now, i.e. no npm module. Your copyright is in the repo of course. I’ll leave a link here when I’m done if anyone else have a need for it.



On 9 December 2016 at 16:54:04, JerryShen (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi @michaelswe<https://github.com/michaelswe> , feel free to do whatever you want :) I currently don't have a plan of migrating it to node.js environment, although, if you need any help, please let me know!

**Comment by michaelswe** [comment]
I solved my needs and put it in a public repo for others to use. I really don't know how to use the MIT license, so I simply put Jerrys original licence file in the repo. I hope that will suffice.

[https://github.com/michaelswe/node-qrcode-svg](url)

**Comment by awesomejerry** [comment]
Nice work! Please consider making it an installable module and publish it to npm!
