### ISSUE TITLE
QR code is not scannable

### ISSUE THREAD

**Issue by Baksha2008** [awesomejerry/react-native-qrcode-svg#100]
Hi guys, my QR code is not scannable, I use RN 0.59.9 in my project. But when I install the library  on a new project with RN 0.61.5 all works perfectly.  Do you have ideas?

**Comment by QuantJames** [comment]
I found that upgrading from RN 0.59.8 to  RN 0.61.x made the QR code not scannable on Android (but it remains fine on iOS). This is because it replaces the individual square pixels with circles. I have not managed to debug this further yet.

**Comment by QuantJames** [comment]
Downgrading react-native-svg to 11.0.1 fixed it for me.

**Comment by Baksha2008** [comment]
> Downgrading react-native-svg to 11.0.1 fixed it for me.

Thanks, I'll try!

**Comment by jrgarciadev** [comment]
> Downgrading react-native-svg to 11.0.1 fixed it for me.

This works for me

**Comment by Yennnful** [comment]
> > Downgrading react-native-svg to 11.0.1 fixed it for me.
> 
> This works for me

Hi @jrgarciadev,  Which version of react-native-qrcode-svg have you used?

**Comment by Sunfocus** [comment]
For me it is still not working.

React-Native: 0.63.3
react-native-qrcode-svg: 6.1.1
react-native-svg: 11.0.1 (also tried the latest version).

This is simple example is not scannable:
```
<QRCode
      size={250}
      value="Hello World"
    />
```

![Screenshot 2021-05-28 at 11 13 37 AM](https://user-images.githubusercontent.com/14137288/119935875-d8a2f780-bfa5-11eb-83f8-e0a5863d5a4b.png)


Please suggest.

**Comment by awesomejerry** [comment]
Can you change the background color to non-black? If you strip the qr code from background, it can be scanned.

**Comment by Sunfocus** [comment]
Thanks @awesomejerry your suggestion works.
