### ISSUE TITLE
Error while updating property fill of a view managed by: RNSVGRect

### ISSUE THREAD

**Issue by mathritter** [awesomejerry/react-native-qrcode-svg#101]
Getting this error:

![image](https://user-images.githubusercontent.com/6000689/78141078-59e21700-7401-11ea-9435-bcc3d8c68f9a.png)

Expo: 3.17.5
react-native-svg: "^11.0.1"
react-native-qrcode-svg: "^6.0.3"

**Comment by awesomejerry** [comment]
It looks nothing to do with this library. Maybe about `react-native-svg`?
