### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNSVGSvgView

### ISSUE THREAD

**Issue by melbinkuriakose** [awesomejerry/react-native-qrcode-svg#102]
![Screenshot_20200414-040601_atom](https://user-images.githubusercontent.com/37395932/79167812-f810ac80-7e05-11ea-879f-2fdb4b09e8b1.jpg)

I am using : 
react native 0.65,
react-native-svg: 12.1.0,
react-native-qrcode-svg: 6.0.3

Anyone has any idea why I am getting this error?
Thanks in advance

**Comment by kkage** [comment]
@melbinkuriakose solve it ?

**Comment by obernardovieira** [comment]
Hi,
Yeah, the problem is with `react-native-svg` version. This package only works with ^9.6.4

Now, my question is, when will this update, since Expo SDK37 uses `react-native-svg` 11? And I want to keep using this.

**Comment by TheAlexandru** [comment]
Tried different versions and still, it doesn't work...

**Comment by obernardovieira** [comment]
For me, the version ^9.6.4 still work on SDK38 (I've updated already)
