### ISSUE TITLE
Unrecognized selecor sent to instance

### ISSUE THREAD

**Issue by SpectorHacked** [awesomejerry/react-native-qrcode-svg#103]
Getting a crash error,
React-Native,
Using expo SDK 36,
Platform: IOS,
Trying to render the QRCode Component but gets this error:

![unnamed](https://user-images.githubusercontent.com/31251714/79998401-54896100-84c3-11ea-90e6-054d316c019e.jpg)

My Code:

`export default class QRCodeShare extends Component {

    constructor(props) {
        super(props);
        this.state = {
            button: 'Add Guest',
            qrCodeValue: this.props.route.params.data,
        }
    }
    componentDidMount() {
        console.log(this.props.route.params.data)
    }
    render() {
        return (
            <ImageBackground style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }} source={BackGroundImage}>
                <QRCode
                    // color="black"
                    // backgroundColor='white'
                    value="test"
                    // logo={iconQR}
                    // logoSize={50}
                />
                <TouchableOpacity style={styles.shareButton}>
                    <Text style={styles.shareButtonText}>Share</Text>
                </TouchableOpacity>
            </ImageBackground>
        );
    }
}`

**Comment by barbhackk** [comment]
Hi, I have exactly the same problem. Is this an Expo problem?

Thanks for your help.

**Comment by barbhackk** [comment]
> Getting a crash error,
> React-Native,
> Using expo SDK 36,
> Platform: IOS,
> Trying to render the QRCode Component but gets this error:
> 
> ![unnamed](https://user-images.githubusercontent.com/31251714/79998401-54896100-84c3-11ea-90e6-054d316c019e.jpg)
> 
> My Code:
> 
> `export default class QRCodeShare extends Component {
> 
> ```
> constructor(props) {
>     super(props);
>     this.state = {
>         button: 'Add Guest',
>         qrCodeValue: this.props.route.params.data,
>     }
> }
> componentDidMount() {
>     console.log(this.props.route.params.data)
> }
> render() {
>     return (
>         <ImageBackground style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }} source={BackGroundImage}>
>             <QRCode
>                 // color="black"
>                 // backgroundColor='white'
>                 value="test"
>                 // logo={iconQR}
>                 // logoSize={50}
>             />
>             <TouchableOpacity style={styles.shareButton}>
>                 <Text style={styles.shareButtonText}>Share</Text>
>             </TouchableOpacity>
>         </ImageBackground>
>     );
> }
> ```
> 
> }`

What is your version of "react-native-svg" in package.json

**Comment by ashrafhariri** [comment]
I resolved the issue by the following:
1- I uninstalled react-native-svg with following command:
npm un react-native-svg
2- I ran the application with:
npm start
3- When it failed to find the react-native-svg module, quit that, and re-installed it by following command:
expo install react-native-svg
