### ISSUE TITLE
Security vulnerability issue

### ISSUE THREAD

**Issue by gbhasha** [awesomejerry/react-native-qrcode-svg#104]
There is a [security issue ](https://github.com/soldair/node-qrcode/issues/163) raised in [node-qrcode](https://github.com/soldair/node-qrcode) and the same has been fixed in their next release v1.3.2.

Currently this library is using node-qrcode@1.2.0 which is vulnerable as per the npm audit report.

As security audit is mandatory for banking, financial apps and enterprise software systems.  Kindly update node-qrcode version to above v1.3.2 or add '^' prefix before the version so that it can be resolved by the user of this library using 'resolutions' field.

Here is the report for this library: https://snyk.io/test/github/awesomejerry/react-native-qrcode-svg

> Denial of Service (DoS)
> Vulnerable module: mem
> Introduced through: qrcode@1.2.0
> Detailed paths
> Introduced through: react-native-qrcode-svg@awesomejerry/react-native-qrcode-svg#2b4aaa7a56d84d429406d12444f95b2b088643c2 › qrcode@1.2.0 › yargs@8.0.2 › os-locale@2.1.0 › mem@1.1.0
> Remediation: Upgrade to qrcode@1.3.3.
> Overview
> mem is an optimization used to speed up consecutive function calls by caching the result of calls with identical input.
> 
> Affected versions of this package are vulnerable to Denial of Service (DoS). Old results were deleted from the cache and could cause a memory leak.
> 
> Denial of Service (DoS) vulnerability report

**Comment by awesomejerry** [comment]
Thanks for the PR! I've released `6.0.6`.
