### ISSUE TITLE
Invalid QR Code

### ISSUE THREAD

**Issue by felipecruz91** [awesomejerry/react-native-qrcode-svg#108]
Hi,

Could anyone help me figuring out why the generation of the QR code is invalid?

Thank you! 

![image](https://user-images.githubusercontent.com/15997951/80286483-ea272980-872b-11ea-80a3-c18d9c0cde75.png)

I'm using the following dependencies:

```
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
"react-native-qrcode-svg": "^6.0.6",
"react-native-svg": "^12.1.0",
```
And the code is based on [this example](https://snack.expo.io/@wodin/qr-code-generator):

```js
import * as React from "react";
import { View, StyleSheet } from "react-native";
import SvgQRCode from "react-native-qrcode-svg";

// Simple usage, defaults for all but the value
function Simple() {
  return (
    <SvgQRCode
      size={200}
      color={"#2e78b7"}
      value="Hello everyone! This is a test!"
    />
  );
}

export default function QRGeneratorScreen() {
  return (
    <View style={styles.container}>
      <View
        style={{
          width: "100%",
          flexDirection: "row",
          justifyContent: "space-around",
          alignItems: "center",
        }}
      >
        <Simple />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "space-around",
    paddingTop: 20,
    alignItems: "center",
    backgroundColor: "#ecf0f1",
  },
});
```

**Comment by tweenietomatoes** [comment]
```
import QRCode from 'react-native-qrcode-svg';
<QRCode
size={200}
color={"#2e78b7"}
value={"Hello everyone! This is a test!"}
    />
```

**Comment by felipecruz91** [comment]
Hi @tweenietomatoes, using `QRCode` instead of `SvgQRCode` didn't solve it.

**Comment by felipecruz91** [comment]
@tweenietomatoes I have added the `onError` parameter to the `QRCode` and I can see that the callback is being fired. However, how could I see the actual error message?

```
import QRCode from 'react-native-qrcode-svg';

function onError() {
  console.log("Something wrong happened");
}

<QRCode
size={200}
color={"#2e78b7"}
value={"Hello everyone! This is a test!"}
onError={onError()}
/>
```

**Comment by awesomejerry** [comment]
You should pass onError directly, not the called function.
```
<QRCode
size={200}
color={"#2e78b7"}
value={"Hello everyone! This is a test!"}
onError={onError}
/>
```

**Comment by EmmanuelSkapple** [comment]
Hi, I had the same error, I could solve it by entering the library and adding the attribute:

`strokeLinecap={'square'}     Line 141  index.js file`
y modifique el algortimo en la clase `./src/tranformMatrixIntoPath.js`

`Line 2   add    const cellSize = size / matrix.length - 0.1`
`Line 9   add            path += `M${cellSize * j+9} ${cellSize / 2 + cellSize * i} ` `

this to adjust the width and some of the squares generated by the algorithm

**Comment by VictorPullzz** [comment]
Please fix this in lib,
I have the same bug

**Comment by snahrvar** [comment]
@EmmanuelSkapple That did the trick for me! I found it odd how the QR Code was shaped, and your solution brought it all together. Looks normal and works now. It would be great if this was the default for the package.

**Comment by EmmanuelSkapple** [comment]
> @EmmanuelSkapple That did the trick for me! I found it odd how the QR Code was shaped, and your solution brought it all together. Looks normal and works now. It would be great if this was the default for the package.

good that it worked for you, hopefully they fix it in the next update

**Comment by Qrysto** [comment]
I get the same issue, please fix this

**Comment by pantelispanayiotou** [comment]
is it fixed? i am still getting the same result...using expo.

**Comment by EmmanuelSkapple** [comment]
> is it fixed? i am still getting the same result...using expo. It works fine on iOS but not on android

It is not fixed yet, you can use the form that I propose above to repair it provisionally, while it is updated by support

**Comment by JohnyDNU** [comment]
Solution from @EmmanuelSkapple did the trick!
> `Line 9 add: path += 'M${cellSize * j+9} ${cellSize / 2 + cellSize * i}' `

Please pay attention that assigned value in this line must be enquoted in `` ` ``, but not in ` ' `
And as for me it's better to increase on 6, not on 9
Line 9 add: ``path += `M${cellSize * j + 6} ${cellSize / 2 + cellSize * i}` ``

**Comment by EmmanuelSkapple** [comment]
> Solution from @EmmanuelSkapple did the trick!
> 
> > `Line 9 add: path += 'M${cellSize * j+9} ${cellSize / 2 + cellSize * i}' `
> 
> Please pay attention that assigned value in this line must be enquoted in `` ` ``, but not in `'`
> And as for me it's better to increase on 6, not on 9
> Line 9 add: `` path += `M${cellSize * j + 6} ${cellSize / 2 + cellSize * i}` ``

Yes sorry for the `'`, 
it worked for me with a +9

**Comment by Qrysto** [comment]
Is this project still alive? Or I need to fork it to fix it? @awesomejerry

**Comment by Qrysto** [comment]
+6 worked for me too

**Comment by awesomejerry** [comment]
> Is this project still alive? Or I need to fork it to fix it? @awesomejerry

It'll be great if you issue a PR!

**Comment by JohnyDNU** [comment]
> Solution from @EmmanuelSkapple did the trick!
> 
> > `Line 9 add: path += 'M${cellSize * j+9} ${cellSize / 2 + cellSize * i}' `
> 
> Please pay attention that assigned value in this line must be enquoted in `` ` ``, but not in `'`
> And as for me it's better to increase on 6, not on 9
> Line 9 add: `` path += `M${cellSize * j + 6} ${cellSize / 2 + cellSize * i}` ``

Ok, with this changes it doesn't fix an issue still. In case of very big encoded values issue is reproduced.
The right way is to change this string as the following: 
`` path += `M${cellSize * (j + 1)} ${cellSize / 2 + cellSize * i}` ``

**Comment by Qrysto** [comment]
> > Is this project still alive? Or I need to fork it to fix it? @awesomejerry
> 
> It'll be great if you issue a PR!

I don't understand the fix so I hesitate to create a PR. Could you review @JohnyDNU's PR and possibly merge it?
