### ISSUE TITLE
update node-qrcode to 1.4.4

### ISSUE THREAD

**Issue by tweenietomatoes** [awesomejerry/react-native-qrcode-svg#110]
can you please update it to 1.4.4 ?

**Comment by AzzouDuGhetto** [comment]
+1, also `node-qrcode` and `qrcode` are two different node_modules. `qrcode` patch some warning (`Require Cycle`) in 1.3.0, it will be great to be able to benefit it when using `react-native-qrcode-svg`

**Comment by tweenietomatoes** [comment]
i did.
