### ISSUE TITLE
Each rectangle seems to be displayed with BorderRadius

### ISSUE THREAD

**Issue by amarcatovic** [awesomejerry/react-native-qrcode-svg#112]
`<QRCode value={this.state.data.userID} />`

[Like here](https://stackoverflow.com/questions/61430757/react-native-expo-qrcode-generate-each-rectangle-with-borderradius#new-answer)

**Comment by anteatersa** [comment]
I have applied the patch found on Stackoverflow and does work:

> For someone who has the same problem, I fixed it like this:
> 
> ADD strokeLinecap={'square'} on Line 141, as property of at index.js file
> 
> Head to tranformMatrixIntoPath.js file and modify the algorithm
> 
> UPDATE Line 2 add const cellSize = size / matrix.length - 0.1 UPDATE Line 9 add path += `M${cellSize * j + 9} ${cellSize / 2 + cellSize * i}`
