### ISSUE TITLE
Best practice for object transformation into QR Code?

### ISSUE THREAD

**Issue by ASchwad** [awesomejerry/react-native-qrcode-svg#113]
Hey there,

I am trying to convert a javascript object to a QR Code.

e.g.:
var car = {type:"Fiat", model:"500", color:"white"}

My current approach is to take each value and create one long string, which i handover as "byte"

value={[{ data: 'Fiat#500#white', mode: 'byte' }]}

Is there a more elegant way? I would like to read the data via another phone with a QR Scanner and get the object.

Thanks in advance!

**Comment by geekazoid-at** [comment]
> Hey there,
> 
> I am trying to convert a javascript object to a QR Code.
> 
> e.g.:
> var car = {type:"Fiat", model:"500", color:"white"}
> 
> My current approach is to take each value and create one long string, which i handover as "byte"
> 
> value={[{ data: 'Fiat#500#white', mode: 'byte' }]}
> 
> Is there a more elegant way? I would like to read the data via another phone with a QR Scanner and get the object.
> 
> Thanks in advance!

Why not use JSON.stringify?
It'll waste a few precious bytes but the Fiat 500 is still small car. *joke*

**Comment by ASchwad** [comment]
I appreciate your humor. I switched to JSON.stringify by now aswell, that's the way to go!
