### ISSUE TITLE
QR Code does not scan [Expo]

### ISSUE THREAD

**Issue by auggustus6** [awesomejerry/react-native-qrcode-svg#114]
The generated qr code does not scan anywhere.
It generates perfectly but when scanning it says it is invalid code

Packages:
 "react-native-svg": "11.0.1",
"react-native-qrcode-svg": "^ 6.0.3",

**Comment by Qamarkh** [comment]
Same issue me, 
<QRCode
                    //QR code value
                    value={[{ data: this.state.ordernumerForQRCode, mode: 'numeric' }]}
                    //size of QR Code
                    size={150}
                    //Color of the QR Code (Optional)
                    color="black"
                    //Background Color of the QR Code (Optional)
                    backgroundColor="white"
                   
                  />

QRcode generating for numeric mode successfully but is not scanning emulator QRCode from mobile scanner nothing happening.

**Comment by DilipCoder** [comment]
In react native 0.62 same issue

**Comment by vishva-shukla** [comment]
Facing the same issue with expo
"expo": "^39.0.0",
"react-native-svg": "12.1.0",
"react-native-qrcode-svg": "^6.0.6",

**Comment by RomanSuvorov** [comment]
In react native 0.64.3 same
