### ISSUE TITLE
is it possible to save QR code as image format in ios ?

### ISSUE THREAD

**Issue by mostasim** [awesomejerry/react-native-qrcode-svg#116]

**Comment by jayzyaj** [comment]
I believe this library is a big help to developers out there. But yes we need to have documentation on how to save this.

**Comment by mostasim** [comment]
Yes absolutely it's a very awesome library for the developers.The
documentation may be improved. Thanks for the library and i have saved the
qr image to gallery in both iOS and Android.

**Comment by jayzyaj** [comment]
@mostasim that’s great. how did u do it for iOS?

**Comment by mostasim** [comment]
@jayzyaj hopefully this snippet will help you.
` saveQrToDisk() {
    let nameQRCode = 'OrderID ' + this.props.pin.orderId;
    this.svg.toDataURL(data => {
      RNFS.writeFile(
        RNFS.CachesDirectoryPath + '/' + nameQRCode + '.png',
        data,
        'base64',
      )
        .then(success => {
          return CameraRoll.save(
            RNFS.CachesDirectoryPath + '/' + nameQRCode + '.png',
            'photo',
          );
        })
        .then(() => {
          this.setState({busy: false, imageSaved: true});
        });
    });
  }`
