### ISSUE TITLE
Couldn't find preset "ES2015" relative to directory

### ISSUE THREAD

**Issue by faizmokhtar** [awesomejerry/react-native-qrcode-svg#12]
I've created a new project to test the module but I get the following error when trying to import the project. I think it's something related with Babel.

![screen shot 2017-03-14 at 4 13 14 pm](https://cloud.githubusercontent.com/assets/1093100/24035853/0f03b51c-0b32-11e7-81b8-4a6a36cda262.png)

Here's my `package.json`

```
{
	"name": "TestGenerateQR",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "~15.4.1",
		"react-native": "0.42.0",
		"react-native-qrcode-svg": "^4.0.0",
		"react-native-svg": "^5.1.5"
	},
	"devDependencies": {
		"babel-jest": "19.0.0",
		"babel-preset-react-native": "1.9.1",
		"jest": "19.0.2",
		"react-test-renderer": "~15.4.1"
	},
	"jest": {
		"preset": "react-native"
	}
}
```

**Comment by faizmokhtar** [comment]
I just realized there's a previous issues #4 that's similar to this . I'll try that one out first and see how it goes. 😅

**Comment by awesomejerry** [comment]
Based on the screenshot you provide, maybe the error is due to wrong app name in the last line of index.ios.js
```
AppRegistry.registerComponent('YourAppName', () => YourAppComponent);
```

**Comment by awesomejerry** [comment]
As for 
```
Couldn't find preset "ES2015" relative to directory
```
I'll try to make the babel preset same as RN which is 
```
       "jest": {
		"preset": "react-native"
	}
```

**Comment by awesomejerry** [comment]
Checkout 4.0.1
I've replace all babel things to `react-native` preset.

**Comment by faizmokhtar** [comment]
@awesomejerry sorry, I attached the wrong image. I've tried 4.0.1 and it's working without altering `babel.rc` anymore. 👌
