### ISSUE TITLE
Doesnt take variable in value prop

### ISSUE THREAD

**Issue by sumanbhattarai** [awesomejerry/react-native-qrcode-svg#122]
If I write the below line as value="suman" , then it works but if i assign a variable name="suman" and use it as below then it doesn't work.
```
 <QRCode value={name} />
```
It will throww an error like this :  
Error: No input text

**Comment by misterlib** [comment]
Just commenting here how I figured out how to use this in case it isn't clear to others. The above sample will work like this:

``<QRCode value={`${name}`} />``

This works for me.
