### ISSUE TITLE
SyntaxError: Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by mrKorg** [awesomejerry/react-native-qrcode-svg#126]
I have RN + RNWeb project.
It works fine with RN android device, but the same code have error with react-native-web.

`
./node_modules/react-native-qrcode-svg/src/index.js
Support for the experimental syntax 'jsx' isn't currently enabled (29:5):
`

**Comment by nguyenthanhkhiem-adcrew** [comment]
node_modules/react-native-qrcode-svg/src/index.js: Support for the experimental syntax 'jsx' isn't currently enabled (29:5):

  27 |
  28 |   return (
> 29 |     <G x={logoPosition} y={logoPosition}>
     |     ^
  30 |       <Defs>
  31 |         <ClipPath id='clip-logo-background'>
  32 |           <Rect

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.

**Comment by papiliond** [comment]
Do you have any progress on this?
