### ISSUE TITLE
Improvements to documentation for saving generated code

### ISSUE THREAD

**Issue by tingzhouu** [awesomejerry/react-native-qrcode-svg#129]
I would like to suggest improvements to the documentation for the section [Saving generated code to gallery for iOS and Android](https://github.com/awesomejerry/react-native-qrcode-svg#saving-generated-code-to-gallery).

The current documentation only provides an example for Android using `react-native-fs`. Here are my suggested improvements:

1. Android - How to save generated code using either `rn-fetch-blob` or `react-native-fs`
2. iOS - How to save generated code

Are the maintainers open to having these improvements? If so, I will be happy to write these improvements and create a pull request.

**Comment by awesomejerry** [comment]
Any PR is welcome!
