### ISSUE TITLE
Is there any way to save the generated SVG to gallery

### ISSUE THREAD

**Issue by MocanuMarius** [awesomejerry/react-native-qrcode-svg#13]
Hey, anyone aware of a method to save that image to gallery or something like that...maybe get the BASE64 info and store it on disk somehow ? Thank a lot :)

**Comment by awesomejerry** [comment]
https://github.com/react-native-community/react-native-svg/issues/212
Will this help?

**Comment by MocanuMarius** [comment]
I'm not sure if it will help, from what i'm seeing that assumes you already have the base64 data of the image, however from this module there is no way i can retrieve the base64 svg contents. I'm pretty sure it's stored somewhere in it's state tho, so one could PR and give us a method to get that data. And yes, whatever you do with it i guess you could use fille system in some way or another to save to disk.

**Comment by awesomejerry** [comment]
You're right. There's a function `toDataURL`. I'll expose a function `getRef` so that you can get SVG ref and call `toDataURL` to get the base64 string.

**Comment by MocanuMarius** [comment]
@awesomejerry thanks a lot, i will maybe submit a PR request after i figure it out and if you want this save to gallery feature. I find it really useful, not much reason in generating a QR code if you're not able to "print" it. :)

**Comment by awesomejerry** [comment]
@MocanuMarius Feel free to make the PR! I'm currently only available for small changes, but I can still merge PR. Thank! 

Just publish @4.0.2 with `toDataURL`

**Comment by MocanuMarius** [comment]
@awesomejerry Great ! I'll test out the new version and how it works this week, and possibilty submit that PR, i don't like that it would bloat it with some dependencies ... but i guess it's sort of an 'essential' feature at least from how i view this module can help you in your app.

**Comment by MocanuMarius** [comment]
@awesomejerry Hey, i haven't found a simple way to do this, and there is no way we can integrate RNFS into this package since it's like 10x size or something so it's not right. Maybe you can post a short tutorial of how i done it tho, this is excerpt from my code on how i save it to gallery using RNFS module : 

_Note: Not sure if it works on iOS , but has been tested on android and it works ok._

import { CameraRoll , ToastAndroid } from "react-native"
import RNFS from "react-native-fs"
  .....
  
  saveQrToDisk() {
		this.svg.toDataURL((data) => {
			RNFS.writeFile(RNFS.CachesDirectoryPath+"/some-name.png", data, 'base64')
			  .then((success) => {
				  return CameraRoll.saveToCameraRoll(RNFS.CachesDirectoryPath+"/some-name", 'photo')
			  })
			  .then(() => {
				  this.setState({ busy: false, imageSaved: true  })
				  ToastAndroid.show('Saved to gallery !!', ToastAndroid.SHORT)
			  })
			  .catch((err) => {
			    console.warn(err.message);
			  });

		})
	}

**Comment by awesomejerry** [comment]
@MocanuMarius 

Let's stick to the `Single Responsibility Principle`. If someone needs to save the svg, just include `RNFS` like you did. 
Your code example looks great! Can you make a Pull Request of adding it to `README.md`?

**Comment by MocanuMarius** [comment]
@awesomejerry Sure, will do !!

**Comment by MocanuMarius** [comment]
#14

**Comment by awesomejerry** [comment]
Merged https://github.com/awesomejerry/react-native-qrcode-svg/pull/14

**Comment by ashishrokr** [comment]
@MocanuMarius  @awesomejerry   Cannot Find  this.svg.toDataURL ..please give working code .Thanks in Advance

**Comment by MocanuMarius** [comment]
@ashishrokr yes there is a problem with my code, the strings "/some-name.png" and "/some-name" should be the same...i forgot it while making it "github-friendly". Try to put the png thing in the second one aswell..if not then there must be a problem with device rights.

**Comment by MocanuMarius** [comment]
@awesomejerry can you update the readme aswell with new snippet after he confirms it works ? Thanks !

**Comment by awesomejerry** [comment]
OK, I'll do the README update!

**Comment by ashishrokr** [comment]
thanks @MocanuMarius  ,it works finally!!! Many thanks @MocanuMarius

**Comment by ebouJ** [comment]
any solution for this. Is there a way to send the generated qr code as an image attachment in React Native ?

**Comment by awesomejerry** [comment]
@ebouJ What do you mean by "send the generated qr code as an image attachment"? 

Maybe this will help
https://github.com/wkh237/react-native-fetch-blob#user-content-upload-example--dropbox-files-upload-api

**Comment by ebouJ** [comment]
So my requirement is to generate a qr code and thanks your library for that. But After I generate the qr code the company should now print the qr code on a paper. So I am saying whether it's possible after I generate the qr code I can send it via email either as image or pdf? @awesomejerry

**Comment by msageryd** [comment]
Do you need to do this from react-native? If not it's very easy to do from node.js with the `qrcode`library (the same as the one used by react-native-qrcode-svg).

Here is an example:

    const QRCode = require('qrcode');

    QRCode.toFile(
      './filename.png',
      'https://yourdomain.com/qr1',
      {
        version: 4,
        errorCorrectionLevel: 'M',
      },
      function(err) {
        if (err) return console.log(err);
        console.log('PNG file saved');
      }
    );

Learn about error version and error correction here: http://www.qrcode.com/en/about/version.html

**Comment by ebouJ** [comment]
@msageryd  thanks for that. I need to do in React Native instead. I'm stuck on this for days

**Comment by awesomejerry** [comment]
For the email sending, the following should work in theory.

https://github.com/chirag04/react-native-mail


```
this.svg.toDataURL((data) => {
    RNFS.writeFile(RNFS.CachesDirectoryPath+"/my-photo.png", data, 'base64')
        .then(() => {
            // use this path for the attachment `RNFS.CachesDirectoryPath+"/my-photo.png"`
        })
})

...

Mailer.mail({
    ...
    attachment: {
        path: PATH_FROM_RNFS,
        type: 'png',   // Mime Type: jpg, png, doc, ppt, html, pdf
        name: 'my-photo',   // Optional: Custom filename for attachment
    }
})
```

Please give it a try!

**Comment by ebouJ** [comment]
I am currently trying it. But what is this.svg? I am getting errors

**Comment by ebouJ** [comment]
Thanks @awesomejerry I finally manage to have it working... Thanks for this wonderful library and your time....
