### ISSUE TITLE
Does it work with react-native-web ?

### ISSUE THREAD

**Issue by kopax-polyconseil** [awesomejerry/react-native-qrcode-svg#145]
Hi, I'd like to know if I can assume this module as react native web compatible. Thanks !

**Comment by timbastin** [comment]
Yes it is! I am using it inside a Web Project.

**Comment by likeSo** [comment]
Yes, it can be displayed in my Expo Web Project!
But i still don't figure out that how can i save the qrcode to a local file.
The`toDataURL` method does not available on web

**Comment by the-habu** [comment]
You sure about react-native-web? For me it always renders just a black box with no errors.
