### ISSUE TITLE
Saving generated code to gallery

### ISSUE THREAD

**Issue by h9ee** [awesomejerry/react-native-qrcode-svg#147]
how can i do that ? 

this code your example 
``import { CameraRoll , ToastAndroid } from "react-native"
import RNFS from "react-native-fs"
...

  saveQrToDisk() {
   	this.svg.toDataURL((data) => {
   		RNFS.writeFile(RNFS.CachesDirectoryPath+"/some-name.png", data, 'base64')
   		  .then((success) => {
   			  return CameraRoll.saveToCameraRoll(RNFS.CachesDirectoryPath+"/some-name.png", 'photo')
   		  })
   		  .then(() => {
   			  this.setState({ busy: false, imageSaved: true  })
   			  ToastAndroid.show('Saved to gallery !!', ToastAndroid.SHORT)
   		  })
   	})
  }
``

but CameraRoll  Is obsolete !

**Comment by soutot** [comment]
You need to import CameraRoll from '@react-native-community/cameraroll'

However, there's an issue on iOS with `toDataURL` that's adding new lines to the base64 data. This new line silently fails the fs.writeFile, because no file is really written in the device. Currently, you can fix this by removing all new lines generated in the base64. Here's a working solution:

```
ref?.current?.toDataURL((data) => {
      const filename =  'some-image-stuff.png'
      const imagePath = `${RNFetchBlob.fs.dirs.CacheDir}/${filename}`

      RNFetchBlob.fs
        .writeFile(
           imagePath,
           data.replace(/\r?\n|\r/g, ''), // THE FIX
           'base64'
        )
        .then(() => {
         CameraRoll.save(imagePath)
            .then(() => {
                console.log('Success')
              })
            .catch((saveError) => console.log({saveError}))
        })
        .catch((writeError) => console.log({writeError))
    })
```

**Comment by h9ee** [comment]
I use this code work for me : 

`  const onShare = () => {
        qrsVG.toDataURL(callback)
    };

    const callback = (dataURL) => {
        console.log(dataURL, "here iam here ");
        let shareImageBase64 = {
            title: 'React Native',
            url: `data:image/png;base64,${dataURL}`,
            subject: 'Share Link', //  for email
        };
        Share.open(shareImageBase64).then((res) => {
            console.log(res);
        })
            .catch((err) => {
                err && console.log(err);
            });
    }
`
you should to install this package  : react-native-share

**Comment by h9ee** [comment]
I use this code work for me : 

`  const onShare = () => {
        qrsVG.toDataURL(callback)
    };

    const callback = (dataURL) => {
        console.log(dataURL, "here iam here ");
        let shareImageBase64 = {
            title: 'React Native',
            url: `data:image/png;base64,${dataURL}`,
            subject: 'Share Link', //  for email
        };
        Share.open(shareImageBase64).then((res) => {
            console.log(res);
        })
            .catch((err) => {
                err && console.log(err);
            });
    }
`
you should to install this package  : react-native-share
