### ISSUE TITLE
Rounded Images

### ISSUE THREAD

**Issue by joncursi** [awesomejerry/react-native-qrcode-svg#16]
I am loading user avatars dynamically over the network and placing them in the middle of the QR code. They are rendered with square corners which looks a little off for my app given that every other avatar in the app is circular (`borderRadius: 50%`).

Is it possible to specify style attributes to the image that gets rendered in the center so I can make it round?

**Comment by awesomejerry** [comment]
I believe that's possible. Current logo implementation is wrapping an `Image` inside a `View`. We can provide `borderRadius` and `overflow` to the `View` and make it rounded.

I'll make a new release for this.

**Comment by awesomejerry** [comment]
https://github.com/facebook/react-native/issues/3198
It turns out Android still not supports `overflow: 'hidden';` and `borderRadius: 50`.
It might not work as expected on Android with my fixing.

Will try some other hacks instead. Feel free to let me know your thought!

**Comment by joncursi** [comment]
Hmm... could you just expose a `logoStyle` prop that gets used as the `style` prop on `View`? This way it's up to the end developer on how they want to style that view. By passing in whatever style options they need. For example, I happen to need circular images, but maybe another developer needs rounded corners (not fully circular.

**Comment by joncursi** [comment]
Are there any red flags with doing that? I guess it could be "dangerous" to let a developer naiively set a bad style like `position: absolute` or something, which will mess up the positioning of the `View` and cause the bar code to not be readable, or perhaps worse, read incorrectly.

Thoughts?

**Comment by msageryd** [comment]
I wouldn't say so. There is always danger in putting an image in a QR code. It only works because QR code has redundancy, but if the image is too big not even the redundant data in the QR will make it work. 

The developer should test to make sure that the logo-QR works as it should. But since ```react-native-qrcode-svg```has started out a bit constrained I think it would make sense to keep that direction, i.e. only expose properties that are reasonable for the use case.

BTW. Fully circular vs rounded corners is only a matter of inputing different corner radii.

**Comment by awesomejerry** [comment]
Thank @joncursi for the proposed way and thank @msageryd for clarifying the point of constrained props and the contribution.

For simplicity, the `logoBorderRadius` might just be fine.

**Comment by awesomejerry** [comment]
I've released https://github.com/awesomejerry/react-native-qrcode-svg/releases/tag/5.0.3. If there's any problem, please re-open this issue.

**Comment by awesomejerry** [comment]
https://github.com/awesomejerry/react-native-qrcode-svg/releases/tag/5.1.0

It solves rounded image
