### ISSUE TITLE
Consistent QR Code

### ISSUE THREAD

**Issue by longtran2613** [awesomejerry/react-native-qrcode-svg#179]
Everytime I reload/render the same screen, the QR Code change even if the value is still the same
Is there a way to have the same QR Code if value doesn't change?
Currently I'm thinking of auto-saving the QR Code somewhere and everytime the screen render, it will check to see if QR Code is already available and value is the same as before, but it feels like a hassle to do so

**Comment by snoodleboot** [comment]
I saw this too. Does it matter if it is changing if it still goes to the same location no matter what? Is it more trouble to store a static image that won't resize well?

**Comment by longtran2613** [comment]
i was using QR Code to hold vCard value (react-native-vcards)
it was changed every render because of it
nothing wrong with the packages
