### ISSUE TITLE
lib support

### ISSUE THREAD

**Issue by wxg3a702** [awesomejerry/react-native-qrcode-svg#2]
I need user the react-native version(react=15.1.0, react-native=0.28.0), then I try to run your lib, nonsupport！Xcode show the error('RCTFont.h' file not found). How would we get over that problem?

**Comment by awesomejerry** [comment]
The problem might be the incompatible version of `react-native-svg` because this module is technically just an implementation based on it.
Can you try to modify the version of `react-native-svg` in `node_modules/react-native-qrcode-svg/package.json` to a lower one and reinstall?

**Comment by awesomejerry** [comment]
Update version, please try if it solves your problem
