### ISSUE TITLE
qrcode-svg version 5.0.5 doesn't work with react version 16.2

### ISSUE THREAD

**Issue by jasoncys** [awesomejerry/react-native-qrcode-svg#21]
Tried the following combinations and couldn't get <QRCode value='hello world'/> to work.

Scenario 1:
react-native-qrcode-svg: version 5.0.5
react-native-svg: version 5.4.1
react: version 16.0.0
==> Error message: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Rect`.

Scenario 2: 
react-native-qrcode-svg: version 5.0.5
react-native-svg: version 6.0.1-rc.1
react: version 16.0.0
=> Error message: No component found for view with name "RNSVGRect"

Do I have to bump down the version of react to 16.0.0-alpha.12 to make it work?

**Comment by msageryd** [comment]
You might have forgotten to link.
Have you run `react-native link`?
N.B don't forget to restart the packager after linking.

**Comment by jasoncys** [comment]
@msageryd I've done "react-native link react-native-svg" but not for "react-native-qrcode-svg".  Do I have to link "react-native-qrcode-svg" as well?

**Comment by msageryd** [comment]
No, just for react-native-svg. Sometimes the `link`command fails. Have you tried to link manually?
The error you get is exactly what to expect without linking.

**Comment by jasoncys** [comment]
@msageryd I didn't try to link manually.  Is there any documentation on link manually? Thanks.

**Comment by msageryd** [comment]
https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by jasoncys** [comment]
@msageryd Finally got it work with the following combination:
react-native-qrcode-svg@5.0.5
react-native-svg@5.5.1
react@16.0.0
react-native@0.51.0

**Comment by awesomejerry** [comment]
There's breaking changes from react-native-svg@6.0.0. I'll see if it needs upgrade.

@msageryd Thanks for the help!

**Comment by msageryd** [comment]
Unfortunately, both version 5 and 6 seems to have a nasty leak. Every <Svg> element that are created stays forever in memory. The leak size seems to be approx proportional to the Svg size, so a small QR code won't matter much. But if you put 100's of QR codes in a list I'd guess that they are stuck in memory until the app is restarted. It could even be worse with Flatlist if the Svg elements are recreated every time it gets visible in the list (I'm guessing).

Hopefully some smart people will find the leak soon.
https://github.com/react-native-community/react-native-svg/issues/278#issuecomment-352272243

**Comment by elewin** [comment]
I ran into this as well, but was able to fix it by running gradlew clean in my android directory, and then rebuilding the app with react-native run-android. Just restarting the packager wasn't quite enough.
