### ISSUE TITLE
Works in expo?

### ISSUE THREAD

**Issue by MichelDiz** [awesomejerry/react-native-qrcode-svg#24]
cheers

**Comment by awesomejerry** [comment]
Suppose not, cuz it depends on a native module: react-native-svg

**Comment by msageryd** [comment]
I think react-native-svg is included in expo's API. I don't use Expo, but I'm almost sure about this.

**Comment by msageryd** [comment]
Found it:
https://docs.expo.io/versions/latest/sdk/svg.html

I suppose it would just be a matter of requiring `Svg` from `expo`instead of `react-native-svg`

**Comment by awesomejerry** [comment]
@msageryd thanks for the docs!

**Comment by MichelDiz** [comment]
I tested out with expo and works. Thank u all! I preciate it.
