### ISSUE TITLE
Result of value from generated QRCode is different from the real value

### ISSUE THREAD

**Issue by nabilalilipaly08** [awesomejerry/react-native-qrcode-svg#26]
I use these codes to generate QRCode for my project. 

`<QRCode
      value='Just some string value'
      size={200}
      logo={Images.logoMtfBlue}
      logoSize={100}`

there is a problem when I add "logo" to my QRCode. The result when I scan the QRCode should be text "Just some sting value" BUT it is not.  The result is random number. but when I just use the value without adding any logo or image, everything is okay. Is there any solution?

**Comment by msageryd** [comment]
Using a logo in a QR-code has to be done with care. When you block the code with a logo you essentially rely on the redundancy that's build into QR-codes. Too low redundancy and/or too large logo will result in an unreadable code.

I'm not completely sure, but it seems that you might have gone too far with the size. Try one or more of these:
- increase the size of the QR-code
- decrease the size of the logo
- increase the Error correction level
