### ISSUE TITLE
Width and height must be > 0 when save barcode.

### ISSUE THREAD

**Issue by zymethyang** [awesomejerry/react-native-qrcode-svg#27]
Hi, I have a problem when saving the QR code. This problem like that: 
width and height must be > 0
createBitmap
Bitmap.java:830
createBitmap
Bitmap.java:776
toDataUrl
SvgViewShadowNode.java:202
toDataUrl
SvgViewModule.java:34
invoke
Method.java
invoke
Method.java
JavaMethodWrapper.java:473
invoke
JavaMethodWrapper.java:374
invoke
JavaModuleWrapper.java:162
run
NativeRunnable.java

**Comment by awesomejerry** [comment]
The default size should be 100. Did you specify the size of the QR Code to 0?
