### ISSUE TITLE
二维码保存下来没有中间的头像

### ISSUE THREAD

**Issue by xuchao321** [awesomejerry/react-native-qrcode-svg#28]
![1524190237 1](https://user-images.githubusercontent.com/28084523/39027168-33a6a45c-4483-11e8-988b-ff2a8f1dfd57.jpg)
二维码保存下来没有中间红色的头像 请问大佬如何一起保存下来

**Comment by awesomejerry** [comment]
目前是透過SVG的toDataURL輸出圖片，而中間的圖示是手動蓋上去的，所以沒有辦法一起保存下來。
不過或許透過react-native-svg提供的Image元件有辦法做到，我目前沒有時間進行這個測試，有機會的話再試試看！

https://github.com/react-native-community/react-native-svg#image

**Comment by Yanzlllll** [comment]
Why didn't you issue in English?

**Comment by awesomejerry** [comment]
Well, a quick translation for the issue.

## The issue 
How to store logo with the QR Code by using toDataUrl?

## The reply
It can't be achieved right now. We're currently using `Image` from  `react-native` to overlap an image on top of the QR Code. Maybe we can try to use `Image` from `react-native-svg` to achieve that.

**Comment by awesomejerry** [comment]
https://github.com/awesomejerry/react-native-qrcode-svg/releases/tag/5.1.0

The new release should solve this issue.
