### ISSUE TITLE
react-native-qrcode-svg@2.0.0 requires a peer of react-native@0.33.0 but none was installed.

### ISSUE THREAD

**Issue by itagakixt** [awesomejerry/react-native-qrcode-svg#3]
I tried as readme show.
Please install react-native-svg first.

npm install react-native-svg --save
react-native link react-native-svg
npm install react-native-qrcode-svg --save

but the following errors are displayed.

npm WARN react-native-qrcode-svg@2.0.0 requires a peer of react@15.3.1 but none was installed.
npm WARN react-native-qrcode-svg@2.0.0 requires a peer of react-native@0.33.0 but none was installed.
npm WARN react-native-qrcode-svg@2.0.0 requires a peer of react-native-svg@4.3.0 but none was installed.
iMac27-no-iMac:AwesomeProjectSVG itagaki$ react-native -v
react-native-cli: 1.0.0
react-native: 0.33.1
iMac27-no-iMac:AwesomeProjectSVG itagaki$ npm install react-native-svg --save
AwesomeProject@0.0.1 /Users/itagaki/testxx/AwesomeProjectSVG
├── UNMET PEER DEPENDENCY react@15.3.2
├── UNMET PEER DEPENDENCY react-native@0.33.1
└── UNMET PEER DEPENDENCY react-native-svg@4.3.1

npm WARN react-native-qrcode-svg@2.0.0 requires a peer of react@15.3.1 but none was installed.
npm WARN react-native-qrcode-svg@2.0.0 requires a peer of react-native@0.33.0 but none was installed.
npm WARN react-native-qrcode-svg@2.0.0 requires a peer of react-native-svg@4.3.0 but none was installed.
npm ERR! code 1
iMac27-no-iMac:AwesomeProjectSVG itagaki$ npm install --save react@15.3.1 
AwesomeProject@0.0.1 /Users/itagaki/testxx/AwesomeProjectSVG
├── UNMET PEER DEPENDENCY react@15.3.1
├── UNMET PEER DEPENDENCY react-native@0.33.1
└── UNMET PEER DEPENDENCY react-native-svg@4.3.1

npm WARN react-native-qrcode-svg@2.0.0 requires a peer of react-native@0.33.0 but none was installed.
npm WARN react-native-qrcode-svg@2.0.0 requires a peer of react-native-svg@4.3.0 but none was installed.
npm WARN react-test-renderer@15.3.2 requires a peer of react@^15.3.2 but none was installed.
npm ERR! code 1
iMac27-no-iMac:AwesomeProjectSVG itagaki$ npm install react-native-svg --save
AwesomeProject@0.0.1 /Users/itagaki/testxx/AwesomeProjectSVG
├── UNMET PEER DEPENDENCY react@15.3.1
├── UNMET PEER DEPENDENCY react-native@0.33.1
└── UNMET PEER DEPENDENCY react-native-svg@4.3.1

npm WARN react-native-qrcode-svg@2.0.0 requires a peer of react-native@0.33.0 but none was installed.
npm WARN react-native-qrcode-svg@2.0.0 requires a peer of react-native-svg@4.3.0 but none was installed.
npm WARN react-test-renderer@15.3.2 requires a peer of react@^15.3.2 but none was installed.
npm ERR! code 1
iMac27-no-iMac:AwesomeProjectSVG itagaki$ react-native link react-native-svg
rnpm-install info Android module react-native-svg is already linked 
rnpm-install info iOS module react-native-svg is already linked 
iMac27-no-iMac:AwesomeProjectSVG itagaki$ npm install react-native-qrcode-svg --save
AwesomeProject@0.0.1 /Users/itagaki/testxx/AwesomeProjectSVG
├── UNMET PEER DEPENDENCY react@15.3.1
├── UNMET PEER DEPENDENCY react-native@0.33.1
├─┬ react-native-qrcode-svg@2.0.0 
│ └── javascript-qrcode@1.0.7  (git+https://github.com/awesomejerry/javascript-qrcode.git#0a51f31226b92ee276d51e10bd98c4989d3549a9)
└── UNMET PEER DEPENDENCY react-native-svg@4.3.1

npm WARN react-native-qrcode-svg@2.0.0 requires a peer of react-native@0.33.0 but none was installed.
npm WARN react-native-qrcode-svg@2.0.0 requires a peer of react-native-svg@4.3.0 but none was installed.
npm WARN react-test-renderer@15.3.2 requires a peer of react@^15.3.2 but none was installed.
iMac27-no-iMac:AwesomeProjectSVG itagaki$ 

could someone help me on this?

**Comment by awesomejerry** [comment]
I'll try to update the dependencies.

**Comment by awesomejerry** [comment]
Update version, please try if it solves your problem
