### ISSUE TITLE
Can it convert this format?

### ISSUE THREAD

**Issue by MrShakes** [awesomejerry/react-native-qrcode-svg#30]
I'm using https://github.com/dtinth/promptpay-qr to generate the qr code value that ends up as shown below, it doesn't seem to display properly using this library, just shows as random dotted lines, is this kind of data supported please? 
Value: `data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2037%2037%22%3E%3Cpath%20fill%3D%22%23ffffff%22%20d%3D%22M0%200h37v37H0z%22%2F%3E%3Cpath%20stroke%3D%22%23000000%22%20d%3D%22M4%204.5h7m2%200h3m1%200h3m2%200h1m3%200h7M4%205.5h1m5%200h1m4%200h3m1%200h5m2%200h1m5%200h1M4%206.5h1m1%200h3m1%200h1m2%200h3m1%200h1m8%200h1m1%200h3m1%200h1M4%207.5h1m1%200h3m1%200h1m1%200h1m1%200h2m1%200h2m2%200h1m2%200h1m1%200h1m1%200h3m1%200h1M4%208.5h1m1%200h3m1%200h1m1%200h1m1%200h1m1%200h1m1%200h1m1%200h1m1%200h1m1%200h1m1%200h1m1%200h3m1%200h1M4%209.5h1m5%200h1m2%200h2m2%200h1m5%200h1m2%200h1m5%200h1M4%2010.5h7m1%200h1m1%200h1m1%200h1m1%200h1m1%200h1m1%200h1m1%200h1m1%200h7M13%2011.5h1m2%200h1m1%200h1m2%200h3M4%2012.5h2m3%200h3m1%200h2m1%200h2m2%200h1m1%200h1m1%200h1m3%200h2M4%2013.5h1m6%200h2m1%200h1m3%200h2m1%200h2m2%200h2m5%200h1M5%2014.5h4m1%200h2m1%200h1m1%200h2m2%200h3m1%200h1m1%200h1m2%200h1m1%200h2M5%2015.5h2m1%200h1m2%200h1m2%200h2m6%200h2m4%200h1M4%2016.5h1m1%200h2m2%200h5m2%200h2m1%200h1m1%200h5m1%200h1m3%200h1M4%2017.5h4m1%200h1m1%200h1m1%200h2m1%200h1m1%200h1m1%200h1m7%200h2m2%200h1M7%2018.5h2m1%200h5m2%200h1m1%200h1m1%200h1m2%200h2m5%200h1M4%2019.5h4m1%200h1m1%200h1m1%200h1m2%200h3m1%200h1m2%200h1m2%200h1m2%200h1m1%200h1M5%2020.5h1m3%200h5m2%200h2m2%200h1m2%200h1m1%200h1m2%200h2m1%200h1M4%2021.5h1m1%200h3m2%200h4m3%200h1m1%200h2m1%200h2m2%200h2M4%2022.5h2m2%200h4m1%200h2m1%200h3m1%200h2m1%200h7m1%200h2M4%2023.5h1m1%200h1m4%200h2m2%200h1m5%200h2m5%200h2M4%2024.5h1m2%200h1m1%200h5m1%200h1m3%200h1m2%200h8m1%200h1M12%2025.5h3m1%200h3m2%200h2m1%200h1m3%200h1m3%200h1M4%2026.5h7m1%200h1m4%200h3m2%200h3m1%200h1m1%200h1m1%200h2M4%2027.5h1m5%200h1m1%200h2m2%200h2m3%200h2m1%200h1m3%200h4M4%2028.5h1m1%200h3m1%200h1m3%200h4m2%200h9m3%200h1M4%2029.5h1m1%200h3m1%200h1m2%200h2m4%200h1m2%200h1m5%200h1M4%2030.5h1m1%200h3m1%200h1m2%200h1m1%200h2m5%200h1m2%200h2m1%200h1m2%200h1M4%2031.5h1m5%200h1m1%200h1m2%200h1m6%200h3m2%200h2m2%200h2M4%2032.5h7m1%200h2m1%200h1m3%200h2m2%200h1m1%200h2m1%200h1m2%200h1%22%2F%3E%3C%2Fsvg%3E`

**Comment by awesomejerry** [comment]
Do you want to present a QR Code of your base64 string or the value from the QR Code generated by the base64 string? Either way, I think it's all working fine. Please let me know more detail about your issue. :)
![simulator screen shot - iphone 6 - 2018-07-05 at 15 21 08](https://user-images.githubusercontent.com/6601073/42308115-374936b8-8067-11e8-94ce-03280af54894.png)
![simulator screen shot - iphone 6 - 2018-07-05 at 15 21 23](https://user-images.githubusercontent.com/6601073/42308117-3779fd8e-8067-11e8-80ef-a8dc3dbf5f43.png)

**Comment by MrShakes** [comment]
QR code please, mine is looking like the first image, how did you get it to look like the second?

**Comment by awesomejerry** [comment]
It seems that you have a svg file format string. Maybe you can use this `https://github.com/target/react-native-svg-parser` to convert it into `react-native-svg` compatible components.

FYI, the second one is derived from the value of the SVG image directly.
