### ISSUE TITLE
How to Change backgound color of the qr code image 

### ISSUE THREAD

**Issue by arghya95** [awesomejerry/react-native-qrcode-svg#31]
How to Change backgound color of the qr code image ??since it is white by default.I want change the background image.but how??

**Comment by awesomejerry** [comment]
Have you try `backgroundColor` prop?

```
<QRCode
  color='white'
  backgroundColor='black'
/>
```

**Comment by arghya95** [comment]
yes It is working.This prop is missing in your readme.md @awesomejerry .
But I have a problem.The QR code is not scannable when I set backgroundColor as black and foreground color as white.Why this happening?Please help.Thank You

**Comment by awesomejerry** [comment]
You must set the surrounding color of the QRCode to an alike color of backgroundColor. For example, if the backgroundColor is black, the surrounding color should be black-wise to make the QR Code distinguished.

**Comment by awesomejerry** [comment]
@arghya95 I'll make a new release ASAP for the `README.md`. Thanks!
