### ISSUE TITLE
Logo Size

### ISSUE THREAD

**Issue by Albert0405** [awesomejerry/react-native-qrcode-svg#33]
Hi, i was experimenting with the size of the logo and only 28% of the QR code size can be put in the logo size for it to be scan-nable...... could it be possible to increase the size of the logo, let just say up to 50% because i cant no longer scan the qr code if the logo size is above 29% of the actual qr code size

**Comment by awesomejerry** [comment]
Have you tried to set `ecl` to `H`? That'll increase the fault tolerance.

**Comment by Albert0405** [comment]
Yes and still not working

**Comment by awesomejerry** [comment]
https://www.wikiwand.com/en/QR_code#/Error_correction
According to wiki, only 30% of codewords can be restored with `H` ecl. Maybe that's the limitation of QR Code.

**Comment by Albert0405** [comment]
Ok thanks
