### ISSUE TITLE
RNSVGSvgViewManager.toDataURL

### ISSUE THREAD

**Issue by cakesoft-rajesh-puranik** [awesomejerry/react-native-qrcode-svg#36]
getDataURL() {
  this.svg.toDataURL(this.callback);
}
callback(dataURL) {
  console.log(dataURL);
}
render() {
  return (
    <QRCode
      value="Just some string value"
      getRef={(c) => (this.svg = c)}
    />
  );
}

Implemented same way.....

Getting error "Undefined is not an object ('evaluating  RNSVGSvgViewManager.toDataURL')"

**Comment by awesomejerry** [comment]
It seems that you didn't link `react-native-svg` so that the bridge could not find the native module.
Please go check if you successfully link it.

https://github.com/react-native-community/react-native-svg#installation

**Comment by cakesoft-rajesh-puranik** [comment]
Checked in iOS.... Linked with native code by using react-native link react-native-svg
![simulator screen shot - iphone 7 plus - 2018-07-17 at 15 51 45](https://user-images.githubusercontent.com/33144455/42822302-5571458c-89f8-11e8-9f86-503639a59944.png)

**Comment by awesomejerry** [comment]
Can you try to link the module manually? It's only three steps: https://github.com/react-native-community/react-native-svg#ios, or check out your XCode project to see if there's `RNSVG.xcodeproj` in `Libraries`.
<img width="288" alt="2018-07-17 22 40 52" src="https://user-images.githubusercontent.com/6601073/42824609-bede88e4-8a12-11e8-9cf0-f11dbe192907.png">
