### ISSUE TITLE
Logo is not showing

### ISSUE THREAD

**Issue by Sterlingryan** [awesomejerry/react-native-qrcode-svg#37]
**Code** 
  `<QRCode
         value={this.props.renterref}
          size={200}
          logo={require('../assets/images/tick.png')}
           logoBackgroundColor='transparent' />`

**react-native-qrcode-svg version**: 5.1.0
**react-native-svg version**:5.5.1

**Comment by Sterlingryan** [comment]
To whoever has the same problem, update the react-native-svg version. I set mine to 6.3.1 and it was solved

**Comment by fanmaoyu0871** [comment]
i resolve this my problem as you see, but we need to use the newest version. i don't know the reason is react-native-qrcode-svg  or react-native-svg ? if have this issue, author should not to update the denpends. @awesomejerry @Sterlingryan

**Comment by awesomejerry** [comment]
The reason is that `react-native-svg` should be in newer version.
The `peerDependencies` has been updated as below:
```
  "peerDependencies": {
    "react-native": ">=0.46.0",
    "react": "*",
    "react-native-svg": "^6.5.2"
  }
```
