### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by pablen** [awesomejerry/react-native-qrcode-svg#39]
Hi, and thanks for this package!

Could you please update and publish a new version updating `react-native-svg` dependency to latest version `6.5.2`? I can confirm this package works fine with it.

This would prevent the following npm warning:

```npm WARN react-native-qrcode-svg@5.1.0 requires a peer of react-native-svg@^5.4.1 but none is installed. You must install peer dependencies yourself.```

**Comment by awesomejerry** [comment]
Sorry for the late reply. OK I'll publish a new version later!
