### ISSUE TITLE
Babel trouble

### ISSUE THREAD

**Issue by michaelswe** [awesomejerry/react-native-qrcode-svg#4]
I'd really want to try out this module. But I get all kinds of trouble. I see that you have committed a new .babelrc a couple of days ago. Might this module be in kind of an unstable shape for the moment? Or is the problem with my setup?

Node 6.9
RN 0.36.1  (also tried with 0.34)

Problems I get:
**"Couldn't find preset ES2015..."**
- Shouldn't npm modules install whatever dependencies they need? Including Babel stuff?

**"Unmet peer dependency react-native-svg@^4.3.1"**
"peer dep missing: react-native-svg@^4.3.1, required by react-native-qrcode-svg@3.0.0"
- But I have 4.3.1 installed

**"Transform error.. Invalid option"**
![image](https://cloud.githubusercontent.com/assets/4483085/20077907/a1dae342-a53e-11e6-9eb3-f8b25b81c207.png)

**Comment by awesomejerry** [comment]
The problem might be that I put those modules in "devDependencies", so that it doesn't get installed while you run `npm install`. Can you manually install them by now? 
```
npm i --save-dev babel-plugin-transform-class-properties babel-preset-es2015 babel-preset-react
```
Also make the following alter to make those modules applied
`.babelrc`
```
{
  "presets": ["es2015", "react"],
  "plugins": ["transform-class-properties"]
}
```
Will make the change later, or try to make it module-independent as possible

**Comment by michaelswe** [comment]
Thank you for:

- A speedy answer which helped
- A great module

`npm i --save-dev babel-plugin-transform-class-properties babel-preset-es2015 babel-preset-react` did the trick.

I use react-native-svg in my project anyway, so it's a good fit to use your module for generating QR codes. It seems fast as well. I switched from react-native-qrcode. Preliminary result is that your module is much faster.

Any plans for implementing logotype imprinting? I actually don't know the details, but I have seen QR codes with a logotype in the middle.

**Comment by awesomejerry** [comment]
Glad you like it! About the logotype imprinting, I'll find my time to implement it. Feel free to participate!

**Comment by Calvin-Huang** [comment]
@awesomejerry 
Hi, there
This module is pretty high quality and there are UnitTest within. It's awesome!
But I think add `babel-plugin-transform-class-properties` `babel-preset-es2015` `babel-preset-react` into the RN project is overkill.
Maybe we can remove the configs in `.babelrc`?

**Comment by Calvin-Huang** [comment]
@awesomejerry
Hi, there
This module is pretty high quality and there are UnitTest within. It's awesome!
But I think adding babel-plugin-transform-class-properties babel-preset-es2015 babel-preset-react into the RN project is overkill.
Maybe we can remove the configs in .babelrc?

**Comment by awesomejerry** [comment]
Thanks! My current project is not using this module though, but I'll still try to find some time to give it a renewal, trying to make dependencies more reasonable and remove those presets to make it more general.
PR is welcomed :)
