### ISSUE TITLE
QrCode length overflow.The amount of data is too big.

### ISSUE THREAD

**Issue by priyangamani** [awesomejerry/react-native-qrcode-svg#40]
![screen shot 2018-09-21 at 10 48 05 am](https://user-images.githubusercontent.com/6038069/45857587-09114d00-bd8c-11e8-89ea-6030eee36555.png)

How to resolve the size more than 1076?

**Comment by awesomejerry** [comment]
How big is your data exactly?

https://en.wikipedia.org/wiki/QR_code#Storage

**Comment by priyangamani** [comment]
The length of the string is around 2,453

**Comment by awesomejerry** [comment]
@priyangamani I'm gonna close this issue first. If yours not resolved, please re-open it.
