### ISSUE TITLE
Logo don't show in Android

### ISSUE THREAD

**Issue by DwCleb** [awesomejerry/react-native-qrcode-svg#41]
I'm using this lib in my application, and is simple and fast. But in Android the image logo don't show in QrCode.

` 
<QRCode
   value="my value"
   size={200}
   logo={require('img/qr_icon.png')}
   logoSize={80}
   logoBackgroundColor="transparent"
/>`

I imported the lib:
`import QRCode from 'react-native-qrcode-svg';`

On iPhone is allright, fantastic, but in the Android the logo don't show....
Why?

**Comment by DwCleb** [comment]
So, I resolved my issue with issue #37 .

**Comment by awesomejerry** [comment]
Glad you solved it!
