### ISSUE TITLE
logo is not working

### ISSUE THREAD

**Issue by TranHanHieu** [awesomejerry/react-native-qrcode-svg#42]
I have 1 QR code, i want to display the logo in that QR, I passed it a base64 uri but it does not work

**Comment by awesomejerry** [comment]
Do you pass the logo via `{ uri: YOUR_BASE64_STRING }`?

**Comment by superdopey** [comment]
I am having the same issue.

I tried a 30x30 png as base64 -->didn't work
I tried a 30x30 png as localfile (using require) --> didn't work

I then converted the file to a jpg but with the same results.

**Comment by awesomejerry** [comment]
Have you updated `react-native-svg` version as this issue https://github.com/awesomejerry/react-native-qrcode-svg/issues/37 indicated?

**Comment by superdopey** [comment]
Yes, that did the trick. Thx for the help and thank you for a great library :)

**Comment by awesomejerry** [comment]
@TranHanHieu I'm gonna close this issue first. If yours not resolved, please re-open it.
