### ISSUE TITLE
svgRef.toDataURL() works on iOS but crash on Android + EXPO

### ISSUE THREAD

**Issue by jaimebiernaski** [awesomejerry/react-native-qrcode-svg#43]
Hi,

I'm using Expo, and according to [documentation](https://github.com/react-native-community/react-native-svg#automatic), react-native-svg is already linked.

I'm trying to use  `getRef={c => (this.qrcode = c)}` to send the SVG as png,

but when

 ```
this.qrcode.toDataURL(base64 => {
        this._callback(base64);
      });
```
It crashes only on Android with the error:

> TypeError: undefined is not an object (evaluating 'RNSVGSvgViewManager.toDataURL')

On iOS, it works perfectly!

Some idea?

 "react-native-qrcode-svg": "^5.1.1",
 "react-native-svg": "^6.5.2",

**Comment by awesomejerry** [comment]
Maybe the problem lies on how expo link native module like `react-native-svg` on Android or the version of `react-native-svg` in `expo` is outdated?

**Comment by samipshah100** [comment]
Sorry for bumping. 

I am having same issue using RN (without expo):
    "react-native": "0.60.5",
    "react-native-qrcode-svg": "^5.2.0",
    "react-native-svg": "^9.13.3",

anyone has a workaround? basically i need to save the QR code image as a base64 string or image file.
