### ISSUE TITLE
Could not find method implementation() for arguments

### ISSUE THREAD

**Issue by kapil708** [awesomejerry/react-native-qrcode-svg#44]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/kapil/Desktop/ReactNativeApplication/demoApps/qrcodecreator/node_modules/react-native-svg/android/build.gradle' line: 52

* What went wrong:
A problem occurred evaluating project ':react-native-svg'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.de
pendencies.DefaultDependencyHandler.

**Comment by awesomejerry** [comment]
It looks like the problem is from `react-native-svg` and gradle version.

Check out this issue to see if it solves your problem:
https://github.com/react-community/react-native-languages/issues/13
