### ISSUE TITLE
[Bug] "This is a QR Code."

### ISSUE THREAD

**Issue by thoth-ibl** [awesomejerry/react-native-qrcode-svg#45]
Hi @awesomejerry ,
Sometime QRCode got "This is a QR Code." value.

```
"react-native-qrcode-svg": "^5.1.1",
"react-native-svg": "^7.0.3"
```

**Comment by awesomejerry** [comment]
The default value of `value` is `This is a QR Code`. You may pass `null` in order to not fallback to default value.

@msageryd What do you think? Should it be a default value of `value`?
