### ISSUE TITLE
Ability to handle generating errors

### ISSUE THREAD

**Issue by gaykov** [awesomejerry/react-native-qrcode-svg#47]
Hello,

I'd like to discuss the possibility of adding some kind of an error callback to the library. 

I've started seeing the following error in crashlytics from users: `Error: Error: The amount of data is too big to be stored in a QR Code`. I've seen the #40 issue and probably setting `ecl="L"` would work, but I think we need some more systematic solution because Node's QRCode library throws a lot of errors https://github.com/soldair/node-qrcode/blob/master/lib/core/qrcode.js which could cause crashes in the app.

I think it would be enough to wrap this line:
https://github.com/awesomejerry/react-native-qrcode-svg/blob/bc8baf286bb6d3ba49fe5675af7db99bdfde4639/src/genMatrix.js#L4
with `try...catch` and call an error callback.

What do you think about it?

**Comment by awesomejerry** [comment]
Yeah that will do it. Maybe add `onError` prop for the component as well.
