### ISSUE TITLE
i have problem to use react-native-qrcode-svg + expo

### ISSUE THREAD

**Issue by knopsod** [awesomejerry/react-native-qrcode-svg#51]
Hello
My project create with create-react-native-app, i have problem to use react-native-qrcode-svg + expo
when I type terminal npm start or npm start --reset-cache
have this message in chrome browser -> Unable to resolve "react-native-svg" from "node_modules/react-native-qrcode-svg/src/index.js"
I google this problem and I found react-native-svg are Expo built-in not need to npm install react-native-svg
but my project still can not to run both install or not install react-native-svg
Have any idea or suggestion?
Sorry, my poor english

**Comment by metaheap** [comment]
I am getting the same error on the latest expo :(

**Comment by seanahrens** [comment]
I'm having this same problem. 

`expo --version
2.13.0`

`npm WARN react-native-qrcode-svg@5.1.2 requires a peer of react-native-svg@^6.5.2 but none is installed. You must install peer dependencies yourself.`

`npm list react-native react-native-svg
/Users/solo/Code/Contacts/navtest
├─┬ expo@32.0.6
│ └── react-native-svg@8.0.10 
├── react-native@0.57.1 
└── UNMET PEER DEPENDENCY react-native-svg@9.3.6 `

Expo includes react-native-svg though so if I try to install it, I'll get a different error. Something like this: https://github.com/react-native-community/react-native-svg/issues/591 `Tried to register two views with the same name RNSVGPath`.

So if I don't install react-native-svg, I cannot run the app. And if I do, I cannot run the app. I can't figure any way to use this QR code library. Is downgrading the Expo SDK the only way? If so, to what version?

**Comment by mmariach** [comment]
got it running with expo 32, maybe a lucky hit. by searching this issue i found this 
https://github.com/73R3WY/react-native-svg-animations/issues/13#issuecomment-441374425

move react-native-svg to peerDependencies @ package.json
`  "peerDependencies": {
    "react-native-svg": "^9.3.6"
  },`

**Comment by MrSamsa42** [comment]
> move react-native-svg to peerDependencies @ package.json
> ` "peerDependencies": { "react-native-svg": "^9.3.6" },`

Can you please outline the series of steps taken to get this work? I tried moving the dependency on a  newly-created expo project, and I still get the error, "Tried to register two views with the same name RNSVGRect."  

This is what my package.json file looks like:
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-qrcode-svg": "^5.1.2"
  },
  "peerDependencies": {
    "react-native-svg": "^9.3.7"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}`

**Comment by awesomejerry** [comment]
No problem with the latest `expo` on ios. Here's `package.json`:
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-qrcode-svg": "^5.1.2"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}
```

All I do is:
`expo init MY_PROJECT`
`cd MY_PROJECT`
`yarn add react-native-qrcode-svg`

**Comment by mmariach** [comment]
Your right. If you just paste the line 
`"react-native-qrcode-svg": "^5.1.2" `
in your package.json and run: npm install. Then every thing seems to work nice. 

If you follow the installation instructions 
`npm install react-native-svg --save`
`react-native link react-native-svg`
`npm install react-native-qrcode-svg --save`
you run into that problem.

**Comment by rphlmr** [comment]
@mmariach  You have to run `expo install react-native-svg ` first ;)

It'll do that for you (you have nothing to do) :
```
npm install react-native-svg --save
react-native link react-native-svg
```

**Comment by billtlee** [comment]
Hi, I am having a problem getting qr code to work.  Here is what I did
npx expo-cli init myapp
npx expo-cli install react-native-qrcode-svg
then add qrcode element into app
Got this error:
Unable to resolve "react-native-svg" from "node_modules/react-native-qrcode-svg/src/index.js"
Failed building JavaScript bundle.

Here is my package.json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "axios": "^0.19.0",
    "ethers": "^4.0.33",
    "expo": "^34.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-qrcode-svg": "^5.1.2",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.1"
  },
  "devDependencies": {
    "babel-preset-expo": "^6.0.0"
  },
  "private": true
}

**Comment by rphlmr** [comment]
@billtlee
Did you do 'expo install react-native-svg first' ?

**Comment by billtlee** [comment]
@rphlmr 
Thanks! That was it.  I thought react-native-svg was part of expo.
