### ISSUE TITLE
Logo not working on ios

### ISSUE THREAD

**Issue by bachlongkocanh** [awesomejerry/react-native-qrcode-svg#54]
Logo working on android but not ios

**Comment by cwlin0416** [comment]
If specific logoSize larger than 20 will not show correctly on iOS.

**Comment by cwlin0416** [comment]
> If specific logoSize larger than 20 will not show correctly on iOS.

problem resolved after upgrade react-native-svg 9.3.5 to 9.3.7

**Comment by bachlongkocanh** [comment]
> > If specific logoSize larger than 20 will not show correctly on iOS.
> 
> problem resolved after upgrade react-native-svg 9.3.5 to 9.3.7

I upgraded react-native-svg to 9.3.7 but still issues.

**Comment by awesomejerry** [comment]
Can you provide more error message? Looks fine on my end.

**Comment by bramski** [comment]
I used the suggested version of react-native-svg@6.5.2 and had no issues. I recommend the author to upgrade since react-native-svg is now at 9.3.7.

**Comment by bramski** [comment]
I tried with version 5.5.1 and had issues, found this post, and updated the dependency to the suggested version.

**Comment by bachlongkocanh** [comment]
Update react-native-svg worked for me! Thank for support, i will close issue.
