### ISSUE TITLE
Crash on Android Pie

### ISSUE THREAD

**Issue by ncuthbert** [awesomejerry/react-native-qrcode-svg#56]
App is crashing when running on Android Pie on emulator.

Appears to be related to clipPath and clipRect being deprecated since Android 26:
[https://developer.android.com/reference/android/graphics/Canvas#clipPath(android.graphics.Path,%20android.graphics.Region.Op)](https://developer.android.com/reference/android/graphics/Canvas#clipPath(android.graphics.Path,%20android.graphics.Region.Op))

Could also be related to this issue with react-native-svg:
[https://github.com/react-native-community/react-native-svg/issues/766](https://github.com/react-native-community/react-native-svg/issues/766)

Getting the following error when rendering a QR code:

> Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
checkValidClipOp
    Canvas.java:779
clipPath
    Canvas.java:1007
clip
    VirtualNode.java:263
draw
    RenderableShadowNode.java:213
run
    GroupShadowNode.java:82
traverseChildren
    VirtualNode.java:349
drawGroup
    GroupShadowNode.java:73
draw
    GroupShadowNode.java:64
run
    SvgViewShadowNode.java:193
traverseChildren
    SvgViewShadowNode.java:282
drawChildren
    SvgViewShadowNode.java:188
drawOutput
    SvgViewShadowNode.java:140
onCollectExtraUpdates
    SvgViewShadowNode.java:122
dispatchUpdates
    ReactShadowNodeImpl.java:325
applyUpdatesRecursive
    UIImplementation.java:968
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
applyUpdatesRecursive
    UIImplementation.java:959
updateViewHierarchy
    UIImplementation.java:700
dispatchViewUpdates
    UIImplementation.java:654
onBatchComplete
    UIManagerModule.java:663
onBatchComplete
    NativeModuleRegistry.java:136
onBatchComplete
    CatalystInstanceImpl.java:145
run
    NativeRunnable.java
handleCallback
    Handler.java:873
dispatchMessage
    Handler.java:99
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:193
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:764

**Comment by ncuthbert** [comment]
Updated react-native-svg to latest in my dependencies

**Comment by iwashi1t** [comment]
I also faced the same problem. The problem seems to be fixed in `react-native-svg` version 7.0.0, but `react-native-qrcode-svg` has a version 6.5.2 dependency.

Could you please update and publish a new version updating `react-native-svg` dependency?
