### ISSUE TITLE
生成的二维码无法识别

### ISSUE THREAD

**Issue by orzhtml** [awesomejerry/react-native-qrcode-svg#57]
生成的二维码无法识别，生成的二维码无法在微信里面识别。
![QQ20190603-163159](https://user-images.githubusercontent.com/5866002/58787832-343b8400-861d-11e9-9b64-58f1a8dfb34c.png)

**Comment by orzhtml** [comment]
![QQ20190603-163159](https://user-images.githubusercontent.com/5866002/58787863-47e6ea80-861d-11e9-843d-2cf9dad56437.png)

**Comment by awesomejerry** [comment]
請你試試看把顏色對調：color: 'black', backgroundColor: 'white'

**Comment by orzhtml** [comment]
我用的 svg 是 8.0.8 版本的： "react-native-svg": "^8.0.8"   
尝试下载了 rn-qrcode-svg 的例子，是能扫码，难道是我svg版本太高？

**Comment by orzhtml** [comment]
> 請你試試看把顏色對調：color: 'black', backgroundColor: 'white'

O(∩_∩)O谢谢
