### ISSUE TITLE
Logotype imprinting

### ISSUE THREAD

**Issue by michaelswe** [awesomejerry/react-native-qrcode-svg#6]
Thanks again for a superb module.

I have implemented logotype imprinting in a fork, and I have some design questions before making a PR.

**svg/bitmap**
I have only implemented svg based logos. Would it be of interest if I also implement bitmap logos?

**Bounding box**
I need the bounding box for the svg path in order to fit it well. the simplest solution is to get the svg width and height explicitly via props. This is the solution I have implemented for now. More work for the user, less work for me =)

Another solution is to either fork or depend on this: https://github.com/icons8/svg-path-bounding-box

Yet another solution might be to wait for getBBox() to be implemented in react-native-svg. See:
https://github.com/react-native-community/react-native-svg/issues/89

**Many props**
As of now I need quite some props from the user. Is this ok, or does it seem bloated?

    static propTypes = {
      /* what the qr code stands for */
      value: PropTypes.string,
      /* the whole component size */
      size: PropTypes.number,
      /* the color of the cell */
      color: PropTypes.string,
      /* the color of the background */
      backgroundColor: PropTypes.string,
      /* a svg-string logo to imprint on the QR code,*/
      logo: PropTypes.string,
      /* logo width in pixels */
      logoWidth: PropTypes.number,
      /* logo height in pixels */
      logoHeight: PropTypes.number,
      /* should a background rectangle be painted under the logo? */
      paintLogoBackground: PropTypes.bool
      /* scale factor for your svg logo. Play with this to ensure your QR is scannable */
      logoScale: PropTypes.number
    };

**Example**
Here is a QR code with an imprinted svg paw. The svg is exported from PhotoShop.
![image](https://cloud.githubusercontent.com/assets/4483085/20184194/20f4508e-a768-11e6-89a3-853e4417877c.png)

Here is the code for the above example:

    <QRCode
      size={150}
      value= { 'test' }
      color='#6897bb'
      logoWidth={ 20 }
      logoHeight={ 20 }
      logo='M15.926,4.939 C15.316,7.067 13.742,8.484 12.412,8.105 C11.082,7.725 10.498,5.692 11.109,3.564 C11.720,1.437 13.293,0.019 14.623,0.399 C15.953,0.779 16.537,2.812 15.926,4.939 ZM6.539,0.013 C5.173,0.231 4.349,2.179 4.699,4.364 C5.049,6.550 6.440,8.146 7.806,7.928 C9.173,7.710 9.997,5.762 9.647,3.577 C9.297,1.391 7.906,-0.205 6.539,0.013 ZM1.324,6.033 C0.054,6.537 -0.376,8.446 0.362,10.297 C1.101,12.148 2.729,13.239 3.999,12.735 C5.268,12.231 5.699,10.322 4.960,8.471 C4.221,6.621 2.593,5.529 1.324,6.033 ZM18.746,7.404 C17.490,6.868 15.835,7.918 15.049,9.750 C14.264,11.582 14.646,13.501 15.903,14.036 C17.159,14.572 18.814,13.522 19.600,11.690 C20.385,9.859 20.002,7.939 18.746,7.404 ZM15.773,18.876 C17.324,17.233 13.095,10.439 9.993,10.298 C6.751,10.151 1.815,17.470 3.507,19.157 C5.199,20.845 8.301,19.439 9.993,19.157 C11.685,18.876 13.381,21.411 15.773,18.876 Z'}
      logoScale={ 1.55 }
      paintLogoBackground={ true}
      backgroundColor= 'white'  />

**Comment by awesomejerry** [comment]
Thanks for the great work! My original roadmap was to support a png/jpg logo because logos tends to be in that format when they're used in App Store / Google Play as far as I know, so it feels natural for me. However, supporting as more formats as possible seems great as well.

It seems a little verbose to use logotype IMHO:
- Can the logoWidth be used as logoHeight? Let's say logoSize, cuz logos are ofter square, right?
- logoScale looks like a development-only props, so it's unnecessary?
- paintLogoBackground should be a must-have and go directly as the color of the background to make the logo standing out.

**Comment by michaelswe** [comment]
You are right. I got carried away with the svg stuff, but I'ts probably not needed. I doubt that people are making poster sized QR codes, so there is no need for vector based logotypes.

I disagree with "logos are often square", though. But that's not a big issue with bitmaps since we can use _resizeMode='contain'_.

For flexibility I think that the user needs to have the option to set the color of the logoBackground. I for one will need to set this to 'transparent' so I can have full control over the design myself, i.e. create the logo background myself in the bitmap.

So, my fork does not have svg support anymore. I ditched it in favor of bitmaps. The code is still in the git history, but I frankly don't think it's needed.

How about this:

      /* what the qr code stands for */
      value: PropTypes.string,
      /* the whole component size */
      size: PropTypes.number,
      /* the color of the cell */
      color: PropTypes.string,
      /* the color of the background */
      backgroundColor: PropTypes.string,

      /* an image source object. example {uri: 'base64string'} or {require('pathToImage')} */
      logo: PropTypes.object,

      /* logo width in pixels, defaults to 20% of size */
      logoSize: PropTypes.number,

      /* the logo gets a filled rectangular background with this color. Use 'transparent'
         if your logo already has its own backdrop. Default = same as backgroundColor */
      logoBackgroundColor: PropTypes.string


example:

    //30 pixel logo from base64 string
    <QRCode
      size={100}
      value='test'
      color='black'
      logo={{uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAA..'}
      logoSize={30}
      logoBackgroundColor='transparent'
      backgroundColor= 'white'  />


    //20 pixel logo from file, default size, default background
    <QRCode
      size={100}
      value='test'
      color='black'
      logo={require('../assets/logo.png')}
      backgroundColor= 'white'  />

**Comment by awesomejerry** [comment]
It's great! I'm gonna merge it and make some small alters!
