### ISSUE TITLE
Dependencies Need Upgrading

### ISSUE THREAD

**Issue by bramski** [awesomejerry/react-native-qrcode-svg#60]
`react-native-svg` 6.5.2 is broken on android 9.0
Please upgrade this projects dependency to 9.5.1. I'm having no problems running at that version.

**Comment by honter36** [comment]
I have the same problem, if you need help I can make that update in the code

**Comment by awesomejerry** [comment]
That'll be great! Currently I'm not having enough time for this project.

**Comment by sapjax** [comment]
` react-native-qrcode-svg@5.1.2" has incorrect peer dependency "react-native-svg@^6.5.2".`

I think it's just a `peerDependency`, we can install the lastest `react-native-svg` version and ignore this warning.
