### ISSUE TITLE
Unable to hide component

### ISSUE THREAD

**Issue by LeoIsasmendi** [awesomejerry/react-native-qrcode-svg#66]
QRCode is unable to hide using style

`
<QRCode
                style={{visibility:"hidden"}}
                value={this.state.text}
                size={200}
              />
`

**Comment by awesomejerry** [comment]
We're not passing `style` prop to the component currently. Can you wrap it with a
```
<View style={{visibility:"hidden"}}>
  <QRCode />
</View>
```

**Comment by LeoIsasmendi** [comment]
Yes, I already did that after submitting this issue, but my question is why is not possible setting directly in the QRCode component instead of wrapping with a view? It's possible or a bug?

**Comment by awesomejerry** [comment]
It's possible. It looks like `Svg` component can accpet `style` prop. Would you like to submit a PR?

**Comment by LeoIsasmendi** [comment]
Sure no problem
