### ISSUE TITLE
Not working on Android Pie

### ISSUE THREAD

**Issue by RazaShehryar** [awesomejerry/react-native-qrcode-svg#67]
Hi

I've been trying to use the library on Android pie but it doesn't seem to work. I can't change the color as well as background color of the QR Code and nothing is being generated as well. 

Any suggestions?

**Comment by naderhak** [comment]
Hi i have the same issue as above 
please if there any solution for that 

thanks

**Comment by RazaShehryar** [comment]
> Hi i have the same issue as above
> please if there any solution for that
> 
> thanks

For some reason, the dependency react-native-svg is not working well if you've created your project using Expo. However, it it working fine with react-native cli.

More details to follow: https://github.com/react-native-community/react-native-svg/issues/1115

**Comment by naderhak** [comment]
so what should i do for the expo ?

**Comment by RazaShehryar** [comment]
> so what should i do for the expo ?

I am not sure yet. A few versions ago, it was working fine. I guess you'll have to wait for Expo to resolve this issue. On the other hand, the good news is you can implement your own QR Code with custom logo using free API which is available online.

**Comment by naderhak** [comment]
thanks a lot for your help

**Comment by vedev9** [comment]
Same problem on android 8 with expo sdk33.0.0. 
Did you find any workaround?

**Comment by kivanov82** [comment]
+1 
Used to work in Expo but fails now

**Comment by RazaShehryar** [comment]
> Same problem on android 8 with expo sdk33.0.0.
> Did you find any workaround?

The issue is with the dependency library react-native-svg and not react-native-qrcode-svg itself. I guess expo released their 35.0.0 a while ago on Android 8+. I haven't tried it yet though. Last time I used it with version 34.0.0 and faced the issued which I posted on react-native-community/react-native-svg#1115

At that time, I had couple of options. First one was to use paid version of rapidAPI which provides QR code services along with your logo. you just have to provide your data in the parameters of the url. Other option was to use free version of an online library (I forgot the name though), which simply generated a QR Code without any logo. I had to make it a custom component and place my image as logo at the center (position: 'absolute') of the QR Code.

**Comment by robertobrogi** [comment]
Hi all, i have the same problem.....
I work with expo 35.0.0 and i use the react-native-svg and work fine all but not qrcode....
there is something wron in the render where draw the svg...

in ios is all perfect

**Comment by robertobrogi** [comment]
the problem is this:

<Rect width={size} height={size} fill={backgroundColor} />

if you remove work fine....

**Comment by FahadAlbukhari** [comment]
@robertobrogi more explanation please!

**Comment by awesomejerry** [comment]
I've tried expo@35.0.0 with the following setup, and it's not working. So I do believe that the issue lies within `react-native-svg`'s `Rect`.

```
   <View style={styles.container}>
      <Svg height='50%' width='50%' viewBox='0 0 100 100'>
        <Rect
          x='15'
          y='15'
          width='70'
          height='70'
          stroke='red'
          strokeWidth='2'
          fill='yellow'
        />
      </Svg>
    </View>
```

I'll leave this issue open for further information.

**Comment by maxwedwards** [comment]
@robertobrogi @awesomejerry 

As suggested, I removed the line `<Rect width={size} height={size} fill={backgroundColor} />` and it works. Is there an issue open with `react-native-svg` for this? I couldn't find one.

**Comment by maxwedwards** [comment]
@robertobrogi with expo?

**Comment by robertobrogi** [comment]
@maxwedwards yes expo 35.0.0

**Comment by maxwedwards** [comment]
`Rect` is not working for me either.

Works:
```           
<View>
  <Svg height="100" width="100">
    <Circle cx="50" cy="50" r="50" fill="pink" />
  </Svg>
</View>
```

Does not work:

```            
<View>
  <Svg height="100" width="100">
    <Rect x='15' y='15' width='100' height='100' stroke='red' strokeWidth='2' fill='yellow' />
  </Svg>
</View>
```

In fact if I include the `Rect` the navigation header I have in my app doesn't show. I just get a blank page.

**Comment by maxwedwards** [comment]
As discussed on #1175 over on RN-SVG, if you fix the version to `"9.9.2"` (without the tilde) it works.

**Comment by maxwedwards** [comment]
Also fixing `react-native-svg` at `"9.9.5"` works for me.

**Comment by awesomejerry** [comment]
@maxwedwards Thanks for the info! You really save this project!

**Comment by anforu** [comment]
@maxwedwards Thanks Sir ❤️ 
Works in android with : 
"react-native-qrcode-svg": "^5.3.1",
"react-native-svg": "^8.0.11",

**Comment by Wellbrito29** [comment]
already fixed?

**Comment by SnehalAgrawal** [comment]
Here is an example of [Generation of QR Code in React Native](https://aboutreact.com/generation-of-qr-code-in-react-native/) using [react-native-qrcode-svg](https://github.com/awesomejerry/react-native-qrcode-svg)
