### ISSUE TITLE
Support quiet zone/margin

### ISSUE THREAD

**Issue by sseppola** [awesomejerry/react-native-qrcode-svg#71]
When saving QR codes to the library they do not include any margin, making them undreadable on a dark background.

Would you accept a PR to support more of the [options in node-qrcode](https://github.com/soldair/node-qrcode#renderers-options)?

**Comment by awesomejerry** [comment]
PR is always welcome :D

**Comment by sseppola** [comment]
Initially I thought I would just have to pass the options to the node-qrcode lib, however on closer inspection I saw that we'd need to modify how the svg renders.

My current thinking is that we can support a quiet zone quite easily by just nesting the qr svg and using viewBox, scaling it and positioning it using `x`, `y`, `width`, and `height` to make the svg handle scaling automatically.

```jsx
<Svg ref={getRef} width={size} height={size}>
  <Svg width={size - margin} height={size - margin} x={margin} y={margin}>
    {/* QR content here */}
  </Svg>
</Svg>
```

One question I have after reading the code and comparing it to other solutions, why did you choose to draw paths instead of rects?
This is what `react-qr-svg` does: https://github.com/no23reason/react-qr-svg/blob/master/src/components/qr-svg.js#L47

**Comment by sseppola** [comment]
@awesomejerry let me know if you have any concerns or if there's anything I can do to make it easier to review PR #73 :)

**Comment by awesomejerry** [comment]
Sorry, I'm occupied by other projects currently. Haven't got the time to do the deep review. Will do it maybe this weekend.

As for path/rect drawing, that's just what I want to try (SVG path drawing) when I made this project. Maybe rect drawing is better :D

**Comment by sseppola** [comment]
Ok, no worries :)

Using rects would make it easy to change the squares for different shapes, which could be a cool feature. Perhaps for the future.

**Comment by PrgrmmrOleg** [comment]
is it implemented?
Can i add padding now?

**Comment by sseppola** [comment]
Isn't it faster to try than to ask? 😅
It's a long time ago, but the PR was merged, so I suppose you can. 

https://github.com/awesomejerry/react-native-qrcode-svg/pull/73

**Comment by PrgrmmrOleg** [comment]
Who else will face this question, for this there is a **quietZone** property 


This is not entirely obvious. But this will fix the bug with reading on a dark background in android.
