### ISSUE TITLE
Calling bridge.imageLoader is deprecated and will not work in newer versions of RN. Please update to themoduleForClass API or turboModuleLookupDelegate API.

### ISSUE THREAD

**Issue by yangfanyu** [awesomejerry/react-native-qrcode-svg#72]
warn: setUpDeveloperTools.js:73 Calling bridge.imageLoader is deprecated and will not work in newer versions of RN. Please update to themoduleForClass API or turboModuleLookupDelegate API.

RN 0.61  iphoneX

**Comment by yangfanyu** [comment]
`
<QRCode value={user._id}
                        size={codeSize}
                        logoSize={logoSize}
                        logoBorderRadius={5}
                        logo={user.head ? {uri: Store.getPictureUrl(user.head)} : require('../../imgs/head_default.png')}
                />
`

**Comment by yangfanyu** [comment]
<QRCode value={user._id}
                        size={codeSize}
                        logoSize={logoSize}
                        logoBorderRadius={5}
                        logo={user.head ? {uri: Store.getPictureUrl(user.head)} : require('../../imgs/head_default.png')}
                />

**Comment by awesomejerry** [comment]
I don't think this is related to this package, so I'm gonna close this issue for now.
