### ISSUE TITLE
Cant work with RN 0.60.5

### ISSUE THREAD

**Issue by PinelliaTime** [awesomejerry/react-native-qrcode-svg#74]
"react-native": "0.60.5",
"react-native-svg": "^9.11.1",
"react-native-qrcode-svg": "^5.2.0",

It can work well on simulator，but when i open it on real phone(IOS 13.1),it show the next error info:
![image](https://user-images.githubusercontent.com/41352992/66698749-34f2ce00-ed13-11e9-8941-9a7474e9e2d4.png)

I have poded the react-native-svg,but it still cant work,so,how can i do to make it work on real phone well?
I'm hopeing for your info,thanks very much!

**Comment by DevChenwei** [comment]
"pod install"   is ok

**Comment by awesomejerry** [comment]
Yes, you should do what @DevChenwei said to install native modules.
