### ISSUE TITLE
NOT RENDERING ON ANDROID

### ISSUE THREAD

**Issue by magicmanj27** [awesomejerry/react-native-qrcode-svg#75]
Hi I was attempting to use this repo to generate a qr code, but unfortunately I am unable to make it work on android.

**Comment by awesomejerry** [comment]
Are you using expo? If so, there's a issue regarding to not working on Android. https://github.com/awesomejerry/react-native-qrcode-svg/issues/67

**Comment by robertobrogi** [comment]
open the library and remove 

<Rect width={size} height={size} fill={backgroundColor} />

and work fine

**Comment by anteatersa** [comment]
> open the library and remove
> 
> `<Rect width={size} height={size} fill={backgroundColor} /> `
> and work fine

This is the correct solution for Android.
