### ISSUE TITLE
logoBorderRadius attribute doesn't work on ios

### ISSUE THREAD

**Issue by paopaomo** [awesomejerry/react-native-qrcode-svg#82]
Hi

I tried to set the logoBorderRadius property to make the logo rounded, but it didn't work on ios

react-native-qrcode-svg: 5.3.2
react-native-svg: 9.11.1
react-native: 0.60.5

How to solve this problem?

**Comment by Andriiklymiuk** [comment]
Did you solve it?

**Comment by awesomejerry** [comment]
I've release 6.0.0. It works for me. Please let me know if upgrading solves your issue.

**Comment by paopaomo** [comment]
> @paopaomo Try to downgrade to 5.2.0 version to make logoBorderRadius work

I updated to 6.0.0 and solved the problem, thank you.

**Comment by paopaomo** [comment]
> I've release 6.0.0. It works for me. Please let me know if upgrading solves your issue.

The upgrade will solve the problem, thank you very much
