### ISSUE TITLE
Logo not accepting external styles

### ISSUE THREAD

**Issue by praveenkumar-outlook** [awesomejerry/react-native-qrcode-svg#83]
Hi,

We want rectangular logo inside QR image. But the `QRCode` component is accepting only `logoSize` as prop, which sets both `width` and `height` of the same.

Our solution needs,
* Either accepting external styles for logo
* Or accepting both width and height for logo as props

Thanks.

**Comment by awesomejerry** [comment]
Hi, sorry for the late reply. Do you want something like this https://github.com/awesomejerry/react-native-qrcode-svg/pull/85 ?

You can pass `logoSize` as an object
```
<QRCode
  logoSize={{width: 100, height: 80}}
/>
```

**Comment by praveenkumar-outlook** [comment]
Yes, this will help. If you can accept external styles for logo, that will solve many problems for the same.

**Comment by awesomejerry** [comment]
It seems that it's not a needed feature. So I'm going to close this issue for now. Feel free to re-open it.
