### ISSUE TITLE
Set physical size of the QRCode instead of pixel size

### ISSUE THREAD

**Issue by tannguyen16** [awesomejerry/react-native-qrcode-svg#92]
Hi Jerry,

Thank you very much for the package!

I wonder if there is anyway for me to set the physical size of the QRCode instead of the pixel size. For example, if I want my QR Code to have the same size of 1.5 inches across multiple devices, would there be a way to do it?

Thank you!

**Comment by awesomejerry** [comment]
You can get the dpi of current device and calculate the proper size of the QR Code.

Reference:
https://stackoverflow.com/questions/56451288/get-screen-dpi-in-react-native
https://www.pixelcalculator.com/index.php?round=&FORM=3&DP=1&FA=&lang=en&mm1=1.5&mm2=1.5&dpi1=160&sub1=+calculate+#a1

**Comment by tannguyen16** [comment]
Hi @awesomejerry,

Thank you very much for your help! I actually tried the Pixel calculator method. 

But it seems like if I pass in a constant to the 'size' of the QR Code, for example `size={300}`, it would render QR Code at almost the same size on different phones, just slightly different.

When I use the pixel calculator method, I passed in the dynamic size, which is something like `size={PixelRatio.get() * 160 * 1.33}` with the goal to achieve the QR Code that have the size of 1.33 inches, it actually renders very differently on different phones. For example, it renders a very big QR Code on the phone that have 480dpi (`PixelRatio.get() === 3`). 

Would you have any solution for this?

Thank you,
Tan.

**Comment by awesomejerry** [comment]
Is that not the intended behavior? The bigger the DPI is, the more the pixels it can have in the same length of inches. I think that's why the size are different on different phones.  Not an expert on this though. :P

**Comment by tannguyen16** [comment]
Yeah, it's a bit opposite of what I think it would be. I thought the 300-pixels QR Code on a lower DPI phone would be much smaller than the 300-pixel QR Code on a higher DPI phone. But it turns out to have almost (but still not) the same size. I will dig more into it though. But it's not really an issue for this library so I will close it :D 

Thanks for your help, @awesomejerry !
