### ISSUE TITLE
iOS space between QR Code Pixels

### ISSUE THREAD

**Issue by felix4321** [awesomejerry/react-native-qrcode-svg#93]
I created a react native app with expo. I run it as an expo web app.

When I display a QR code with a real Iphone 7 or IPad Air 3 there are spaces between the QR pixels. On Not-iOS devices it renders without any problems. I only could test it as expo web app and not as native app.

![qrCodeBug](https://user-images.githubusercontent.com/50043030/74538691-042ed980-4f3d-11ea-8d22-bf0d55d5bc91.png)

It is not reproducible with iOS Simulator on Mac.

Because of the spaces the code cannot be read with my scanner.

I don‘t know what causes that problem... ;)

"expo": "~36.0.2",
"react-native-qrcode-svg": "^6.0.3",
"react-native-svg": "9.13.3", (comes with expo version)

Same problem with:
"react-native-svg": "11.0.1"

**Comment by awesomejerry** [comment]
I have no idea. Please re-open this issue if it is still happening.
