### ISSUE TITLE
Hardcoded white border around QR code

### ISSUE THREAD

**Issue by boyuanfang** [awesomejerry/react-native-qrcode-svg#99]
![image](https://user-images.githubusercontent.com/32655525/77596395-19dadb80-6eb9-11ea-8783-b14ea4ac82ea.png)

It seems to be this line's problem
![image](https://user-images.githubusercontent.com/32655525/77596419-2cedab80-6eb9-11ea-90ee-f58427c9b2b8.png)

either deleting it or make it a prop parameter in the interface will help.

**Comment by awesomejerry** [comment]
This should be fixed in `6.0.5`.
